name: "Qt 6.2.9 - Windows - amd64"

on:
  workflow_dispatch:

jobs:
  build_qt:
    runs-on: windows-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
    steps:
      - uses: actions/checkout@v6
      - name: Setup
        run: |
          choco install -y cmake ninja wget 7zip
      - name: Use sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Download and unpack source
        shell: bash
        working-directory: D:\a
        run: |
          set -o pipefail
          QT_URL="https://download.qt.io/archive/qt/6.2/6.2.9/single/qt-everywhere-opensource-src-6.2.9.tar.xz"
          wget -q "${QT_URL}" -O - | tar xJvf -
      - name: Configure
        shell: cmd
        working-directory: D:\a
        run: |
          mkdir build
          cd build

          REM https://wiki.qt.io/Qt_6.2_Tools_and_Versions#Software_configurations_for_Qt_6.2.9
          REM -debug-and-release -force-debug-info
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          ..\qt-everywhere-src-6.2.9\configure ^
            -prefix D:\a\install ^
            -release -headersclean ^
            -qt-zlib ^
            -nomake examples ^
            -submodules qt5compat,qtdeclarative,qtimageformats,qtmultimedia,qtnetworkauth,qtscxml,qtsvg,qttools,qttranslations,qtwebsockets,qtxmlpatterns ^
            -- -DFEATURE_msvc_obj_debug_info=ON -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
      - name: Build
        shell: cmd
        working-directory: D:\a\build
        env:
          NINJA_STATUS: "[%f/%t (%c/s avg %o/s); ETA: %W (%P)]   "
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          cmake --build . --parallel
      - name: Install
        shell: cmd
        working-directory: D:\a\build
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          cmake --install .
      - name: Download pre-built software rendering DLLs
        shell: bash
        working-directory: D:\a\install\bin
        run: |
          OPENGL32SW_URL="https://download.qt.io/development_releases/prebuilt/llvmpipe/windows/opengl32sw-64-mesa_11_2_2-signed.7z"
          wget -q "${OPENGL32SW_URL}" -O /d/a/opengl32sw.7z
          7z x /d/a/opengl32sw.7z

          D3DCOMPILER_47_URL="https://download.qt.io/development_releases/prebuilt/d3dcompiler/msvc2013/d3dcompiler_47-x64.7z"
          wget -q "${D3DCOMPILER_47_URL}" -O /d/a/d3dcompiler_47.7z
          7z x /d/a/d3dcompiler_47.7z
      - name: Package
        working-directory: D:\a\install
        run: |
          7z a -tzip "../Qt-6.2.9-Windows-amd64.zip" .
      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: "Qt-6.2.9-Windows-amd64"
          path: "D:/a/Qt-6.2.9-Windows-amd64.zip"
